- name: Configure web.config for SQL connection string
  hosts: all
  vars:
    ip_address: 10.0.0.1
    database_name: mydatabase
  tasks:
    - name: Create web.config file
      template:
        src: templates/web.config.j2
        dest: /var/www/html/web.config
