---
- name: Ensure IIS is installed and started 
  hosts: webservers
  become: yes 
  become_method: runas
  become_user: Administrator
  vars_files:
    - vault/secrets.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    service_name: IIS Admin Service   
  tasks:
    - name: Ensure IIS Server is present 
      win_feature:
        name:  Web-Server
        state: present
        restart: no
        include_sub_features: yes
        include_management_tools: yes  
    - name: Ensure latest web files are present
      win_copy:
        src: files/
        dest: c:\inetpub\wwwroot\
        force: yes
    - name: Configure website
      win_template:
        src: templates/web.config.j2
        dest: C:\inetpub\wwwroot\web.config
      vars:
        db_username: "{{ db_username }}"
        db_password: "{{ db_password }}"
      become: true
- name: Ensure IIS is started
      win_service:
        name: "{{ service_name }}"
        state: started