---
- name: Install IIS on Windows
  hosts: webservers
  become: true
  tasks:
  - name: Install IIS Web Server Role
    win_feature:
      name: Web-Server
      state: present
  - name: Start World Wide Web Publishing Service
    win_service:
      name: W3SVC
      start_mode: auto
      state: started