---
# tasks file for create-user

- name: Create ansible user
  win_user:
    name: ansible
    password: Pass1234 # replace with your own encrypted password
    state: present
    groups: Administrators
  become: yes

- name: Check if user is already a member of the group
  win_command: 'net localgroup "Administrators" ansible'
  become: yes
  ignore_errors: yes
  register: result

- name: Add user to the group if not already a member
  win_command: 'net localgroup "Administrators" ansible /add'
  become: yes
  when: "'The specified account name is already a member of the group.' not in result.stderr"